# This is a basic workflow to help you get started with Actions

name: Build and deploy Backend application

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: Build angular application
      SERVICE_LOCATION: ./angular-front/todoMvcWithAngular

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup branch name
        run: |
          echo "BRANCH_NAME=$(echo ${{ github.ref }} | sed -e 's,.*/\(.*\),\1,')" >> $GITHUB_ENV

      - name: ${{ env.SERVICE_NAME }}
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Build angular project
        run: |
          cd ${{ env.SERVICE_LOCATION }}
          npm install
          npm run build

      - name: Build docker images
        run: |
          docker build -t ${{ secrets.DOCKER_USER_NAME }}/devops-training-angular:${{env.BRANCH_NAME}} ${{ env.SERVICE_LOCATION }}

      - name: Login to docker to docker hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USER_NAME }} --password-stdin

